### ISSUE TITLE
Is there a way to configure the interval between two consequent  file change checks?

### ISSUE THREAD

**Issue by tukusejssirs** [micnic/recache#3]
I have created a similar issue at paulmillr/chokidar#1079.

Basically, I need to stop watching files for some extended interval, then notify `recache` to check again the files/folders for changes. Basically, I want to do it synchronously.

Is it possible with `recache`? Or I really need to implement it without a package like `recache` or `chokidar`?

Thanks for the help in advance! :smiley:

**Comment by micnic** [comment]
Not sure I totally understood your use case, but you can use the following code:

```js
const recache = require('recache');
const Cache = require('recache/lib/cache'); // undocumented, internal cache class

const cache = recache('path/to/files');

// DO THIS TO STOP THE WATCHING PROCESS
cache.destroy(); // FSWatchers will be closed and cache will be marked as destroyed, cache will not be usable, FSStats and content will still be available for use

// DO THIS TO RESTART THE WATCHING PROCESS
cache._destroyed = false; // undocumented, mark cache as usable again
cache._watchers = new Map(); // undocumented, reset the container of FSWatchers
Cache.prepareCache(cache/*, optionalCallBack */); // undocumented, restart the watching process
```

If this will work for you I could add 2 new methods like `.stop()` and `.start()` to cover this kind of use case.

**Comment by tukusejssirs** [comment]
Thanks, @micnic, for such a prompt comment of yours! :smiley:

As I understand it, `cache.destroy()` would literally _destroy_ (i.e. delete) the cache containing the current state of files and folders in the watched folder.

I wouldn’t like to destroy anything; I actually want to keep the cache, but stop watching the files (e.g. by issuing `cache.stopWatching()`) until I want to continue watching the files (e.g. by running `cache.continueWatching()`).

**Comment by micnic** [comment]
Actually `cache.destroy()` does a soft "destroy", so it just stops file watching process and marks the cache as not usable, but the current state of the watched folder or files is untouched. You can see it yourself what it does here: https://github.com/micnic/recache/blob/master/lib/cache.js#L125

So you can use `.destroy()` method without any worries for your use case.

**Comment by tukusejssirs** [comment]
After re-reading your first comment, it looks like it _is_ what I want. :wink:

It would be nice if you could make it more user-friendly, i.e. add `.pauseWatching()` and `.continueWatching()`. You said you could create `.stop()` and `.start()` methods, however, IMHO the name of those methods could better reflect what they actually do, but that is just my opinion. :man_shrugging: :wink:

---

However, I can’t make it work. I am sure it has to do with some base JS stuff (async vs sync). Could you help me please? Below is a test script base on the example script from `README.md`. Note that I need to make synchronously. Thanks in advance! :+1:

<details>
   <summary><code>testRecache.js</code></summary>

```js
#!/usr/bin/env node

const Cache = require('recache/lib/cache')  // [Undocumented] Internal cache class
const childProcess = require('child_process')
const recache = require('recache')

const sleepTime = 60  // In seconds

// Start watching files
let cache = rTest()

// Sleep for specified amount of time
console.log('INFO: Starting sleeping for ' + sleepTime + ' milliseconds at ' + new Date() + '.')
childProcess.execSync('sleep ' + sleepTime)
console.log('INFO: Finished sleeping for ' + sleepTime + ' milliseconds at ' + new Date() + '.')

// Stop watching files
rStop(cache)

// Sleep for specified amount of time
console.log('INFO: Starting sleeping for ' + sleepTime + ' milliseconds at ' + new Date() + '.')
childProcess.execSync('sleep ' + sleepTime)
console.log('INFO: Finished sleeping for ' + sleepTime + ' milliseconds at ' + new Date() + '.')

// Continue watching files
rContinue(cache)

function rTest() {
	const path = process.cwd() + '/mc'

	const cache = recache(path, {
		persistent: true,
		store: true
	}, (cache) => {
		console.log('INFO: Cache ready!')
	})

	cache.on('error', (error) => {
		console.log('ERROR: Something unexpected happened')
		console.log(error.stack)
	})

	cache.on('ready', (cache) => {
		console.log('INFO: Cache ready!')
	})

	cache.on('update', (cache) => {
		console.log('INFO: Cache updated!')
	})

	cache.on('directory', (directory) => {
		console.log('addDir : ' + directory.location)
	})

	cache.on('file', (file) => {
		console.log('add : ' + file.location)
	})

	cache.on('change', (element) => {
		if (! element.stats.isDirectory()) {
			console.log('change : ' + element.location)
		}
	})

	cache.on('unlink', (element) => {
		if (element.stats.isDirectory()) {
			console.log('unlinkDir : ' + element.location)
		} else {
			console.log('unlink : ' + element.location)
		}
	})

	cache.on('destroy', () => {
		console.log('INFO: Cache destroyed!')
	})

	return cache
}

function rStop(cache) {
	// Stop watching files
	cache.destroy()  // FSWatchers will be closed and cache will be marked as destroyed, cache will not be usable, FSStats and content will still be available for use
}

function rContinue(cache) {
	// Continue watching files
	cache._destroyed = false     // [Undocumented] Mark cache as usable again
	cache._watchers = new Map()  // [Undocumented] Reset the container of FSWatchers
	Cache.prepareCache(cache)    // [Undocumented] Restart the watching process
}
```
</details

**Comment by micnic** [comment]
Unfortunately you cannot do this synchronously as all the internal process is done asynchronously. I will add this functionality as "fake" synchronous through the 2 methods, I did something similar for another package of mine.

**Comment by micnic** [comment]
@tukusejssirs are you still interested in this functional?
I am planing to add the changes that you need with `.watch()` and `.unwatch()` methods, you may only need to use top-level await to write the code in a synchronous way. Top-level await is supported in node 14.3 and higher, are you using a node version in this range?

**Comment by micnic** [comment]
@tukusejssirs I just release version 0.6.0, it includes two new methods, `.start()` and `.stop()` that would do what you wanted. If you are still interested in this, check it out.

**Comment by tukusejssirs** [comment]
> @tukusejssirs are you still interested in this functional? I am planing to add the changes that you need with `.watch()` and `.unwatch()` methods, you may only need to use top-level await to write the code in a synchronous way. Top-level await is supported in node 14.3 and higher, are you using a node version in this range?

Sorry for late reply. Yes, I am still interested in this. and I use Node v16+.

> @tukusejssirs I just release version 0.6.0, it includes two new methods, `.start()` and `.stop()` that would do what you wanted. If you are still interested in this, check it out.

Thanks!
