### ISSUE TITLE
How to store the cached this._container in FS and reconstruct recache object instantly?

### ISSUE THREAD

**Issue by spidgorny** [micnic/recache#7]
I want to store the recache data to JSON file and initialize recache from that file upon restart.

This is not working.

```
console.log("Cache ready!");
let jsonData = JSON.stringify(cache._container.entries());
console.log(jsonData);
fs.writeFileSync(cacheFile, jsonData);
```

`jsonData` is always empty. Any ideas?

**Comment by spidgorny** [comment]
Nevermind. This works.

```
        let jsonData = JSON.stringify(
          Array.from(cache._container.entries()),
          (key, value) =>
            typeof value === "bigint" ? value.toString() : value, // return everything else unchanged
          2
        );
        fs.writeFileSync(cacheFile, jsonData);
```

Restoring:

```
  if (fs.existsSync(cacheFile)) {
    const data = JSON.parse(fs.readFileSync(cacheFile, "utf8"));
    const cache = recache("not existing");
    cache._container = new Map(data);
    return cache;
  }
```

**Comment by micnic** [comment]
In your case you will loose the ability to resync with the file system. I could implement `import` / `export` options and keep the full `recache` functional, without hacking the internals for `._container`.

If you are interested in this solution, could you please share the reason you need to save the fs state in a JSON file?

**Comment by spidgorny** [comment]
In my use case I don't care about resync - the folder contains archive of images from the camera, will not ever change.
I use (abuse?) recache as a convenient caching layer. When I restart the code I want to load the state from the file quickly to avoid resync.

**Comment by micnic** [comment]
Thanks for the response, yes, your use case is outside of this package target uses, closing the issue.
